name: Build ApplicationPatch

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: ./scripts/publish_all

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./build/*
        retention-days: 1
